### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by berlinsaint** [xiweicheng/tms#10]
有没有发现 搭建后的网站经常会很卡， 我搭建在阿里云2c4g上，没做内存cpu限制；但是习惯性登不进去网页，总是卡在ws连接一个页面。这块对机器性能有要求吗？

**Comment by berlinsaint** [comment]
![image](https://user-images.githubusercontent.com/10629930/61204788-c062c000-a720-11e9-8921-0cb250a96cd7.png)
出问题的时候 登陆后 ，跳这个页面。。。。

**Comment by berlinsaint** [comment]
貌似经常会出现这问题。。。

**Comment by xiweicheng** [comment]
> 貌似经常会出现这问题。。。

需要对静态页面进行缓存加入，可以用nginx的，参考 https://gitee.com/xiweicheng/tms/wikis/TMS%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90nginx%E6%89%BF%E8%BD%BD%E4%BB%8E%E8%80%8C%E5%8A%A0%E9%80%9F%E8%AE%BF%E9%97%AE?sort_id=21985

**Comment by reesebo** [comment]
有几个js一兆多了，ecs主机带宽1M..主要还是穷

**Comment by xiweicheng** [comment]
> 有几个js一兆多了，ecs主机带宽1M..主要还是穷

使用nginx加速静态资源访问吧
