### ISSUE TITLE
关于label标签处理

### ISSUE THREAD

**Issue by Usualminds** [xiweicheng/tms#6]
目前，发现两个关于label标签的问题，如下

1. 每次导入翻译，新增标签时，数据库会同时创建两条相同的标签数据，原因是importController中执行了add和update两个方法导致的，不知道这里是否需要添加判断？
    

            translate.setUpdateDate(new Date());
            translate.setUpdater(WebUtil.getUsername());

            Label label = new Label();
            label.setCreateDate(new Date());
            label.setCreator(WebUtil.getUsername());
            label.setName(updateLabel);
            label.setStatus(Status.New);
            label.setTranslate(translate);

            lblUpdated.add(label);

            translate.getLabels().add(label);

            translate.setSearch(translate.toString());
        }

        Mail mail2 = Mail.instance();

        if (lblUpdated.size() > 0) {
            labelRepository.save(lblUpdated);
            labelRepository.flush();

            mail2.addHref("更新", baseURL, translateAction, projectId,
                    updateLabel);
        }

        translateRepository.save(translates3);
        translateRepository.flush();

        // 只有新建的会打标签
        String[] lbls = new String[0];
        if (StringUtil.isNotEmpty(labels)) {
            lbls = labels.split(",");
        }

        List<Translate> translates = translateRepository.save(translates2);
        translateRepository.flush();

        // 新建的翻译打标签
        String newLabel = "N" + DateUtil.format(new Date(), DateUtil.FORMAT8);
        List<Label> lblNew = new ArrayList<>();
        // 新建的翻译设置search属性
        for (Translate translate : translates) {

            Label label = new Label();
            label.setCreateDate(new Date());
            label.setCreator(WebUtil.getUsername());
            label.setName(newLabel);
            label.setStatus(Status.New);
            label.setTranslate(translate);

            lblNew.add(label);

            translate.getLabels().add(label);

            Set<Label> labels2 = new HashSet<>();
            for (String lbl : lbls) {
                Label label2 = new Label();
                label2.setCreateDate(new Date());
                label2.setCreator(WebUtil.getUsername());
                label2.setName(lbl);
                label2.setStatus(Status.New);
                label2.setTranslate(translate);

                labels2.add(label2);
            }
            labelRepository.save(labels2);
            labelRepository.flush();

            translate.getLabels().addAll(labels2);

            translate.setSearch(translate.toString());

            log(Action.Create, Target.Translate, translate.getId());
        }

        translateRepository.save(translates2);
        translateRepository.flush();`

2. 翻译查找页面，手动删除某条翻译的label标签时，刷新页面，页面会报错，应该是数据库翻译字段无法找到相应标签导致，建议增加容错机制，或者添加删除标签权限管理

**Comment by xiweicheng** [comment]
@Usualminds 你好，这边在最新分支master分支下，验证没有发现你提到的两点问题

针对问题1， 导入时生成标签，除了自定义的标签，系统同时会添加一个过滤标签，便于批量识别查找到批量导入的翻译项。

针对问题2，这边测试下来没有重现问题，可能你那边的代码不是最新版本吧，建议更新到最新master代码。
