### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by JXT-Eden** [xiweicheng/tms#7]
有没有管理员账户？注册必须可以不可以不写邮箱？注册提示邮箱异常失败
![image](https://user-images.githubusercontent.com/9624017/50130736-06a28e80-02ba-11e9-83a3-258b1fb572d2.png)

**Comment by xiweicheng** [comment]
默认用户 super  88888888

**Comment by xiweicheng** [comment]
注册需要配置邮箱服务，系统管理员登录后可配置
