### ISSUE TITLE
tinymce

### ISSUE THREAD

**Issue by berlinsaint** [xiweicheng/tms#9]
Markdown感觉有点弱，界面跟confluence有点像，但是编辑器实在。。
、前端 这快是啥框架。。。感觉不太好改啊，想把 tinymce引入进来，作者指点1下？

**Comment by xiweicheng** [comment]
TMS还有这个编辑器的：https://www.froala.com/wysiwyg-editor

使用的https://aurelia.io框架

**Comment by xiweicheng** [comment]
<img width="1080" alt="屏幕快照 2019-07-14 下午10 13 49" src="https://user-images.githubusercontent.com/9198971/61184840-b5f2e880-a684-11e9-8171-2705763226ba.png">

**Comment by berlinsaint** [comment]
emm不知道为啥， html编辑器始终是打不开的状态，本地只显示一个 标题头；
我估摸这是 js引入问题。。。

**Comment by berlinsaint** [comment]
部署到阿里云后发现可以了， 谢作者，很好的项目
